import React, { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Icon } from '@/components/ui/Icon';
import { STUDENT_ME } from '@/data/mock';

type Feature = 'Attendance' | 'Assignments' | 'Examinations' | 'Performance';
type Role = 'Student' | 'Teacher' | 'Administrator';
const features: Record<Feature, { value: string; change: string; title: string; detail: string; bars: number[] }> = {
  Attendance: { value: '68%', change: 'Below the 75% target', title: 'Attendance, at a glance.', detail: '4 sessions missed this month. Your next class is Calculus & Linear Algebra.', bars: [82, 92, 64, 88, 70, 62, 86] },
  Assignments: { value: '54%', change: '1 assignment needs attention', title: 'Keep coursework moving.', detail: 'Problem Set 6 — Integration Techniques is due in two days.', bars: [55, 66, 52, 81, 72, 54, 80] },
  Examinations: { value: '58%', change: '8% below last assessment', title: 'See assessment patterns.', detail: 'Mathematics is trending down across three recent assessments.', bars: [88, 75, 64, 61, 58, 69, 78] },
  Performance: { value: '71', change: 'Academic Index / 100', title: 'The full academic picture.', detail: 'A single, living view of the signals that shape progress.', bars: [62, 67, 72, 68, 76, 71, 78] },
};
const roles: Record<Role, { heading: string; labels: string[]; values: string[]; note: string }> = {
  Student: { heading: 'Good morning, Maya.', labels: ['Academic Index', 'Attendance', 'Assignments'], values: ['71/100', '68%', '54%'], note: 'Mathematics needs attention before your next assessment.' },
  Teacher: { heading: 'Calculus & Linear Algebra.', labels: ['Students', 'Attendance', 'At risk'], values: ['32', '84%', '6'], note: 'Six students would benefit from early support this week.' },
  Administrator: { heading: 'Institutional overview.', labels: ['Students', 'Course health', 'Risk signals'], values: ['2,480', '91%', '12'], note: 'Twelve course cohorts have an emerging risk signal.' },
};
const fade = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

function Trend({ bars, accent = false }: { bars: number[]; accent?: boolean }) { return <div className="trend">{bars.map((bar, index) => <motion.i key={index} initial={{ height: 0 }} whileInView={{ height: `${bar}%` }} viewport={{ once: true }} transition={{ delay: index * .06, duration: .55 }} className={accent && index === bars.length - 1 ? 'accent' : ''}/>)}</div>; }
function AppShell({ role = 'Student' }: { role?: Role }) { const item = roles[role]; return <div className="app-preview"><aside><div className="app-logo">E<span>IQ</span></div>{['Overview', role === 'Student' ? 'My courses' : 'Academic activity', 'Analytics', 'Intelligence'].map((x, i) => <span className={i === 0 ? 'current' : ''} key={x}><i/> {x}</span>)}<small>{role.toUpperCase()} VIEW</small></aside><div className="app-content"><header><div><p>FALL 2026 · WEEK 8</p><h3>{item.heading}</h3></div><div className="app-avatar">{role === 'Student' ? 'MW' : role === 'Teacher' ? 'EM' : 'AD'}</div></header><div className="app-stat-row">{item.values.map((value, i) => <div key={value}><small>{item.labels[i]}</small><b>{value}</b><em>{i === 1 ? 'Updated today' : '↗ this week'}</em></div>)}</div><div className="app-lower"><div className="mini-chart"><small>ACADEMIC TREND</small><Trend bars={role === 'Student' ? [64, 58, 70, 61, 74, 68, 77] : [65, 75, 68, 82, 77, 85, 88]} accent/></div><div className="app-insight"><span><Icon name="sparkles" size={12}/> EDUIQ INSIGHT</span><p>{item.note}</p><button>View insight <Icon name="arrowRight" size={13}/></button></div></div></div></div>; }

function AIIntelligenceSection() {
  const reduced = useReducedMotion(); const [run, setRun] = useState(-1); const [typed, setTyped] = useState(''); const [analyzing, setAnalyzing] = useState(true); const [activeRef, setActiveRef] = useState(-1); const timeouts = useRef<number[]>([]);
  const answer = 'Your mathematics average has declined from 64% to 58% across the last three assessments.\n\nAttendance is currently 68%, below the recommended threshold.\n\nFocus on calculus fundamentals and schedule two focused study sessions this week.';
  const clear = () => { timeouts.current.forEach(window.clearTimeout); timeouts.current = []; };
  useEffect(() => { if (run < 0) return; clear(); setTyped(reduced ? answer : ''); setAnalyzing(!reduced); setActiveRef(-1); if (reduced) return clear; const later = (callback: () => void, delay: number) => timeouts.current.push(window.setTimeout(callback, delay)); later(() => { setAnalyzing(false); let index = 0; const typer = window.setInterval(() => { index += 2; setTyped(answer.slice(0, index)); if (index >= answer.length) { window.clearInterval(typer); setActiveRef(3); } }, 17); timeouts.current.push(typer as unknown as number); }, 900); later(() => setActiveRef(0), 1250); later(() => setActiveRef(1), 2550); later(() => setActiveRef(2), 4100); return clear; }, [run, reduced]);
  const replay = () => setRun(value => value + 1);
  return <motion.section id="ai" className="assistant-section ai-live-section" initial="hidden" whileInView="visible" viewport={{ amount: .42 }} onViewportEnter={replay} variants={{ visible: { transition: { staggerChildren: .13 } } }}><div className="eduiq-container assistant-grid"><div><motion.p variants={fade} className="product-eyebrow">EDUIQ AI INTELLIGENCE</motion.p><h2 className="ai-reveal-title"><motion.span variants={fade}>Academic intelligence that</motion.span><motion.span variants={fade}>understands the context.</motion.span></h2><motion.p variants={fade}>Ask a question in plain language. EduIQ connects the answer to the learning activity that matters.</motion.p><motion.div variants={{ visible: { transition: { staggerChildren: .08 } } }} className="references">{['Performance', 'Attendance', 'Assignments', 'Exams'].map((label, index) => <motion.span variants={fade} className={activeRef === index ? 'is-active' : ''} key={label}><i/> {label}</motion.span>)}</motion.div></div><motion.div variants={{ hidden: { opacity: 0, x: 24 }, visible: { opacity: 1, x: 0, transition: { type: 'spring', stiffness: 190, damping: 24 } } }} className="assistant-card"><header><div className="assistant-icon"><Icon name="sparkles" size={16}/></div><div><b>EduIQ Assistant</b><small><i/> Academic context active</small></div></header><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35 }} className="assistant-question">Why is my mathematics performance dropping?</motion.div><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .55 }} className="assistant-answer"><span>ANALYSIS</span>{analyzing ? <div className="analysis-loading">Analyzing academic data<span><i/><i/><i/></span></div> : <p>{typed}</p>}</motion.div></motion.div></div></motion.section>;
}

export default function HomePage() {
  const navigate = useNavigate(); const reduced = useReducedMotion(); const [feature, setFeature] = useState<Feature>('Attendance'); const [role, setRole] = useState<Role>('Student');
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: reduced ? 'auto' : 'smooth' });
  const selected = features[feature];
  return <div className="eduiq-site">
    <section className="product-hero"><div className="hero-wash"/><div className="eduiq-container hero-layout"><motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: .1 } } }} className="hero-copy"><motion.p variants={fade} className="product-eyebrow"><Icon name="sparkles" size={13}/> AI-POWERED ACADEMIC INTELLIGENCE</motion.p><motion.h1 variants={fade}>Understand student performance.<br/><span>Improve what happens next.</span></motion.h1><motion.p variants={fade} className="hero-description">EduIQ brings attendance, assignments, examinations and academic performance into one intelligent workspace.</motion.p><motion.div variants={fade} className="hero-actions"><button onClick={() => go('workspace')} className="blue-button">Explore EduIQ <Icon name="arrowRight" size={17}/></button><button onClick={() => go('explain')} className="quiet-button">See how it works <Icon name="arrowRight" size={16}/></button></motion.div><motion.p variants={fade} className="audience"><span/> Students <span/> Teachers <span/> Administrators</motion.p></motion.div>
      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .3, duration: .65 }} className="hero-product"><div className="hero-window-top"><div className="mini-brand">E<span>IQ</span></div><p>ACADEMIC OVERVIEW</p><span className="notification"><i/> 1 new insight</span></div><div className="hero-window-body"><div className="hero-greeting"><div><p>STUDENT WORKSPACE</p><h3>Welcome back, Maya</h3></div><span>Aug 16, 2026</span></div><div className="hero-metrics">{[['Academic Index','71'],['Attendance','68%'],['Assignments','74%'],['Examinations','73%']].map(([label,value],i)=><motion.div key={label} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.55+i*.07}}><small>{label}</small><b>{value}</b></motion.div>)}</div><div className="hero-chart"><div><small>PERFORMANCE TREND</small><span className="chart-key">Last 6 weeks</span></div><svg viewBox="0 0 360 96" preserveAspectRatio="none"><motion.path initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:1.1,delay:.65}} d="M0 70 C34 64 46 41 78 50 S122 76 152 62 S197 26 230 37 S278 68 308 43 S338 40 360 22" fill="none" stroke="#4866dd" strokeWidth="3"/><path d="M0 88H360" stroke="#e9edf7"/></svg></div><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:1}} className="hero-recommend"><span><Icon name="sparkles" size={12}/> AI RECOMMENDATION</span><p>Physics performance is improving. Continue the current study plan.</p><button onClick={() => navigate('/register')}>View insight <Icon name="arrowRight" size={13}/></button></motion.div></div></motion.div></div></section>
    <section id="workspace" className="workspace-section"><div className="eduiq-container"><motion.div initial="hidden" whileInView="visible" viewport={{once:true}} variants={fade} className="section-intro"><p className="product-eyebrow">YOUR COMPLETE ACADEMIC WORKSPACE</p><h2>Everything academic.<br/><span>One intelligent workspace.</span></h2><p>Move from today’s activity to the context behind it without switching tools.</p></motion.div><div className="feature-tabs">{(Object.keys(features) as Feature[]).map(item=><button key={item} onClick={()=>setFeature(item)} className={feature===item?'active':''}>{item}<Icon name="arrowRight" size={14}/></button>)}</div><AnimatePresence mode="wait"><motion.div key={feature} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} className="feature-stage"><div className="feature-copy"><p className="tag">{feature.toUpperCase()} OVERVIEW</p><h3>{selected.title}</h3><b>{selected.value}</b><span>{selected.change}</span><p>{selected.detail}</p><button onClick={() => navigate('/register')} className="text-link">Open workspace <Icon name="arrowRight" size={15}/></button></div><div className="feature-visual"><div className="feature-visual-top"><span>{feature} status</span><i>Live data</i></div><Trend bars={selected.bars} accent/><div className="feature-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></motion.div></AnimatePresence></div></section>
    <section id="explain" className="explain-section"><div className="eduiq-container explain-grid"><div><p className="product-eyebrow">MORE THAN A REPORT</p><h2>EduIQ doesn’t just show the data.<br/><span>It explains what to do next.</span></h2><p className="explain-copy">Every recommendation is grounded in the academic record, so students and educators can act with context and confidence.</p><div className="data-list">{[['Attendance','68%'],['Mathematics','58%'],['Assignments','54%'],['Exam trend','↓ 8%']].map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div></div><motion.div initial={{opacity:0,x:18}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="analysis-panel"><header><div className="ai-glyph"><Icon name="sparkles" size={17}/></div><div><span>EDUIQ INTELLIGENCE</span><h3>Mathematics needs attention.</h3></div></header><p className="analysis-reason">Assessment scores have declined across the last three examinations while attendance remains below the recommended threshold.</p><div className="recommendations"><p>RECOMMENDED ACTIONS</p>{['Review calculus fundamentals','Complete pending assignment','Schedule two focused study sessions'].map((a,i)=><div key={a}><b>0{i+1}</b><span>{a}</span><Icon name="arrowRight" size={14}/></div>)}</div></motion.div></div></section>
    <section id="roles" className="showcase-section"><div className="eduiq-container"><div className="showcase-heading"><div><p className="product-eyebrow">A CONNECTED PLATFORM</p><h2>One platform.<br/><span>Three experiences.</span></h2></div><p>Purpose-built views give every role the clarity needed to make better academic decisions.</p></div><div className="role-tabs">{(Object.keys(roles) as Role[]).map(item=><button className={role===item?'active':''} onClick={()=>setRole(item)} key={item}>{item}</button>)}</div><AnimatePresence mode="wait"><motion.div key={role} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}><AppShell role={role}/></motion.div></AnimatePresence></div></section>
    <AIIntelligenceSection/>
    <section className="flow-section"><div className="eduiq-container"><p className="product-eyebrow">THE EDUIQ FLOW</p><h2>From activity to action,<br/><span>without the guesswork.</span></h2><div className="flow"><div><small>01</small><b>Raw academic data</b><p>Attendance · Assignments · Exams · Grades</p></div><i><Icon name="arrowRight"/></i><div><small>02</small><b>Analysis</b><p>EduIQ finds the patterns across every signal.</p></div><i><Icon name="arrowRight"/></i><div><small>03</small><b>Insight</b><p>Weak subject detected with its contributing factors.</p></div><i><Icon name="arrowRight"/></i><div><small>04</small><b>Action</b><p>A clear, personalized next step.</p></div></div></div></section>
    <section id="students" className="roles-section"><div className="eduiq-container"><p className="product-eyebrow">BUILT FOR THE WHOLE ACADEMIC COMMUNITY</p><div className="role-columns">{[['FOR STUDENTS','Know exactly where to focus.','Track courses, attendance, assignments and exams with recommendations built around your progress.'],['FOR TEACHERS','See how your class is progressing.','Manage academic activity and identify students who need support before they fall behind.'],['FOR ADMINISTRATORS','Understand the institution at a glance.','Monitor academic performance, attendance, courses and risk trends from one connected view.']].map(([tag,title,body])=><article key={tag}><span>{tag}</span><h3>{title}</h3><p>{body}</p><button onClick={()=>go('roles')}>Explore view <Icon name="arrowRight" size={15}/></button></article>)}</div></div></section>
    <section className="trust-section"><div className="eduiq-container"><p>EduIQ is a complete academic workspace</p><div>{['Secure academic workspace','Role-based access','Centralized records','Actionable analytics','AI-powered recommendations'].map(x=><span key={x}><Icon name="check" size={14}/>{x}</span>)}</div></div></section>
    <section className="closing-cta"><div className="eduiq-container"><p className="product-eyebrow">READY WHEN YOU ARE</p><h2>Make every academic decision<br/><span>more informed.</span></h2><p>Bring learning activity, academic performance and intelligence into one connected platform.</p><div><button onClick={()=>navigate('/register')} className="blue-button">Get started <Icon name="arrowRight" size={17}/></button><button onClick={()=>go('workspace')} className="quiet-button">Explore platform</button></div></div></section>
    <footer className="product-footer"><div className="eduiq-container footer-grid"><div><div className="footer-mark">EDU<span>IQ</span></div><p>Academic intelligence for better outcomes.</p></div>{[['Platform','Platform','AI Intelligence','Courses'],['For','Students','Teachers','Administrators'],['Company','About','Contact','Support']].map(([title,...items])=><div key={title}><b>{title}</b>{items.map(item=><button onClick={()=>item==='Courses'?navigate('/courses'):item==='Contact'?navigate('/contact'):undefined} key={item}>{item}</button>)}</div>)}</div><div className="eduiq-container footer-bottom"><span>© 2026 EduIQ. All rights reserved.</span><span>Privacy &nbsp;&nbsp; Terms</span></div></footer>
  </div>;
}
